### ISSUE TITLE
Error: class pl.psnc.dl.ege.exception.ConverterException Couldn't find images directory.

### ISSUE THREAD

**Issue by jure** [sebastianrahtz/oxgarage#6]
I have a Docx document which fails Docx to xHTML conversion with the following error:

```
Error: class pl.psnc.dl.ege.exception.ConverterException

Couldn't find images directory.
```

The minimal reproducible test case (a single TIFF image) can be found here: http://cl.ly/0W1u360d0i2f

**Comment by sebastianrahtz** [comment]
Sorry for silence on this and some other issues, I am recuperating from
surgery at the moment. I will try to get to this soon.

On 22 June 2015 at 12:56, Jure Triglav <notifications@github.com> wrote:

> I have a Docx document which fails Docx to xHTML conversion with the
> following error:
>
> Error: class pl.psnc.dl.ege.exception.ConverterException
>
> Couldn't find images directory.
>
> The minimal reproducible test case (a single TIFF image) can be found
> here: http://cl.ly/0W1u360d0i2f
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sebastianrahtz/oxgarage/issues/6>.
>



-- 

Sebastian Rahtz

Director (Research) of Academic IT

University of Oxford IT Services

13 Banbury Road, Oxford OX2 6NN. Phone +44 1865 283431


Não sou nada.

Nunca serei nada.

Não posso querer ser nada.

À parte isso, tenho em mim todos os sonhos do mundo.

**Comment by jure** [comment]
No worries, Sebastian! Get well soon! I'll take a look at this one beginning next week, I have a feeling it's a simple bug, something like a file extension not being included.

**Comment by ronpshah** [comment]
Hi Jure,

We are facing similar type of error (e.g. Any type of documents converting to TEI P5 XML Document):
Error: class pl.psnc.dl.ege.exception.ConverterException
null

Any suggestion how did you try to fix it?
Currently we are not able to convert into any format.

Thanks,
Ronak
